import "@/styles/globals.css";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["500", "700"],
  variable: "--font-sans",
  subsets: ["latin"],
})

export const metadata = {
  title: "React Quiz Application",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${roboto.variable}`}>{children}</body>
    </html>
  );
}
